enum EventKeyType {
  SOURCE_UPLOAD_LOAD_BTN_CLICK = 'SOURCE_UPLOAD_LOAD_BTN_CLICK',
  SOURCE_UPLOAD_CLOSE_CLOSE_BTN_CLICK = 'SOURCE_UPLOAD_CLOSE_CLOSE_BTN_CLICK',
  SOURCE_UPLOAD_CONTENT_MULTIPLE = 'SOURCE_UPLOAD_CONTENT_MULTIPLE',
  SOURCE_DOWNLOAD_FILE_NAME_INPUT_MULTIPLE = 'SOURCE_DOWNLOAD_FILE_NAME_INPUT_MULTIPLE',
  SOURCE_DOWNLOAD_SAVE_BTN_CLICK = 'SOURCE_DOWNLOAD_SAVE_BTN_CLICK',
  SOURCE_DOWNLOAD_CLOSE_BTN_CLICK = 'SOURCE_DOWNLOAD_CLOSE_BTN_CLICK',
  SOURCE_DOWNLOAD_EXTENTION_CHANGE = 'SOURCE_DOWNLOAD_EXTENTION_CHANGE',
  EDITOR_MENU_OPEN_UPLOAD_BTN_CLICK = 'EDITOR_MENU_OPEN_UPLOAD_BTN_CLICK',
  EDITOR_MENU_OPEN_DOWNLOAD_BTN_CLICK = 'EDITOR_MENU_OPEN_DOWNLOAD_BTN_CLICK',
  EFFECT_LIST_CLOSE_BTN_CLICK = 'EFFECT_LIST_CLOSE_BTN_CLICK',
  EFFECT_GAIN_INPUT_PERCENTAGE = 'EFFECT_GAIN_INPUT_PERCENTAGE',
  SOURCE_LIST_DRAGSTART = 'SOURCE_LIST_DRAGSTART',
  AUDIO_TRACK_DRAGOVER_DROP = 'AUDIO_TRACK_DRAGOVER_DROP',
  PLAYBAR_MULTIPLE = 'PLAYBAR_MULTIPLE',
  AUDIO_PLAY_OR_PAUSE = 'AUDIO_PLAY_OR_PAUSE',
  AUDIO_STOP = 'AUDIO_STOP',
  AUDIO_REPEAT = 'AUDIO_REPEAT',
  AUDIO_FAST_REWIND = 'AUDIO_FAST_REWIND',
  AUDIO_FAST_FORWARD = 'AUDIO_FAST_FORWARD',
  AUDIO_SKIP_PREV = 'AUDIO_SKIP_PREV',
  AUDIO_SKIP_NEXT = 'AUDIO_SKIP_NEXT',
  AUDIO_TRACK_CONTAINER_MULTIPLE = 'AUDIO_TRACK_CONTAINER_MULTIPLE',
  SOURCE_LIST_MULTIPLE = 'SOURCE_LIST_MULTIPLE',
  AUDIO_TRACK_SECTION_MULTIPLE = 'AUDIO_TRACK_SECTION_MULTIPLE',
  FOCUS_RESET_CLICK = 'FOCUS_RESET_CLICK',
  EDIT_TOOLS_CLICK = 'EDIT_TOOLS_CLICK',
  PLAYBAR_EVENT_ZONE_DROP = 'PLAYBAR_EVENT_ZONE_DROP',
  ZOOM_BAR_MOUSE_DOWN = 'ZOOM_BAR_MOUSE_DOWN',
  AUDIO_TRACK_OPTION_CLICK = 'AUDIO_TRACK_OPTION_CLICK',
  EFFECT_LIST_OPEN_MODAL_BTN_CLICK = 'EFFECT_LIST_OPEN_MODAL_BTN_CLICK',
  AUDIO_TRACK_MULTIPLE = 'AUDIO_TRACK_MULTIPLE',
  AUDIO_TRACK_AREA_MULTIPLE = 'AUDIO_TRACK_AREA_MULTIPLE',
  TRACK_LIST_SCROLL = 'TRACK_LIST_SCROLL',
  AUDIO_TRACK_AFTERIMAGE_DROP = 'AUDIO_TRACK_AFTERIMAGE_DROP',
  TRACK_MENU_CLICK = 'TRACK_MENU_CLICK',
  TRACK_SECTION_COLOR_CHANGE = 'TRACK_SECTION_COLOR_CHANGE',
  EFFECT_DELETE_BTN_CLICK = 'EFFECT_DELETE_BTN_CLICK',
  EFFECT_MODIFY = 'EFFECT_MODIFY',
  GAIN_EFFECT_CLICK = 'GAIN_EFFECT_CLICK',
  FADE_IN_EFFECT_CLICK = 'FADE_IN_EFFECT_CLICK',
  FADE_OUT_EFFECT_CLICK = 'FADE_OUT_EFFECT_CLICK',
  COMPRESSOR_EFFECT_CLICK = 'COMPRESSOR_EFFECT_CLICK',
  FILTER_EFFECT_CLICK = 'FILTER_EFFECT_CLICK',
  REVERB_EFFECT_CLICK = 'REVERB_EFFECT_CLICK',
  EFFECT_REVERB_INPUT_MIX_RATIO = 'EFFECT_REVERB_INPUT_MIX_RATIO',
  EFFECT_REVERB_INPUT_TIME = 'EFFECT_REVERB_INPUT_TIME',
  EFFECT_REVERB_INPUT_DECAY = 'EFFECT_REVERB_INPUT_DECAY',
  EFFECT_COMPRESSOR_INPUT_THRESHOLD = 'EFFECT_COMPRESSOR_INPUT_THRESHOLD',
  EFFECT_COMPRESSOR_INPUT_KNEE = 'EFFECT_COMPRESSOR_INPUT_KNEE',
  EFFECT_COMPRESSOR_INPUT_RATIO = 'EFFECT_COMPRESSOR_INPUT_RATIO',
  EFFECT_COMPRESSOR_INPUT_ATTACK = 'EFFECT_COMPRESSOR_INPUT_ATTACK',
  EFFECT_COMPRESSOR_INPUT_RELEASE = 'EFFECT_COMPRESSOR_INPUT_RELEASE',
  EFFECT_FILTER_TYPE = 'EFFECT_FILTER_TYPE',
  EFFECT_FILTER_INPUT_FREQUENCY = 'EFFFECT_FILTER_INPUT_FREQUENCY',
  EFFECT_FILTER_INPUT_Q = 'EFFECT_FILTER_INPUT_Q',
  EFFECT_SETTING_APPLY_BTN_CLICK = 'EFFECT_SETTING_APPLY_BTN_CLICK',
  EFFECT_SETTING_CANCEL_BTN_CLICK = 'EFFECT_SETTING_CANCEL_BTN_CLICK',
  TRACK_SCROLL_AREA_SCROLL = 'TRACK_SCROLL_AREA_SCROLL',
  EFFECT_FADE_IN_INPUT_LENGTH = 'EFFECT_FADE_IN_INPUT_LENGTH',
  EFFECT_FADE_OUT_INPUT_LENGTH = 'EFFECT_FADE_OUT_INPUT_LENGTH'
}

enum EventType {
  click = 'click',
  dblclick = 'dblclick',
  keyup = 'keyup',
  keydown = 'keydown',
  dragstart = 'dragstart',
  dragover = 'dragover',
  dragenter = 'dragenter',
  dragleave = 'dragleave',
  dragend = 'dragend',
  drop = 'drop',
  change = 'change',
  input = 'input',
  mousemove = 'mousemove',
  mousedown = 'mousedown',
  mouseout = 'mouseout',
  scroll = 'scroll'
}

const eventTypes = [
  'click',
  'dblclick',
  'keyup',
  'keydown',
  'dragstart',
  'dragover',
  'dragenter',
  'dragleave',
  'drop',
  'change',
  'input',
  'mousemove',
  'dragend',
  'mousedown',
  'mouseout',
  'scroll'
];

interface EventTargetDataType {
  listener: EventListener;
  bindObj: Object;
}

interface EventDataType {
  eventTypes: EventType[];
  eventKey: string;
  listeners: EventListener[];
  bindObj: Object;
}

export { EventKeyType, EventType, eventTypes, EventTargetDataType, EventDataType };
